import json
from datetime import date, timedelta

# A list of 365 sophisticated words with meanings. 
# (This is a large list to ensure quality for the whole year)
words_data = [
    ("Absolve", "verb", "Set free from blame, guilt, or responsibility.", "दोषमुक्त करना"),
    ("Accolade", "noun", "An award or privilege granted as a special honor.", "सम्मान / पुरस्कार"),
    ("Acumen", "noun", "The ability to make good judgments and quick decisions.", "कुशाग्रता / चतुराई"),
    ("Adulation", "noun", "Excessive admiration or praise.", "अति-प्रशंसा"),
    ("Alacrity", "noun", "Brisk and cheerful readiness.", "तत्परता"),
    ("Ameliorate", "verb", "Make (something bad or unsatisfactory) better.", "सुधारना"),
    ("Anachronism", "noun", "A thing belonging or appropriate to a period other than that in which it exists.", "कालोचित दोष"),
    ("Antithesis", "noun", "A person or thing that is the direct opposite of someone or something else.", "विलोम / विपरित"),
    ("Aphorism", "noun", "A pithy observation that contains a general truth.", "सूक्ति / कहावत"),
    ("Arcane", "adjective", "Understood by few; mysterious or secret.", "रहस्यमय"),
    ("Ascetic", "adjective", "Characterized by severe self-discipline and abstention from all forms of indulgence.", "तपस्वी / संयमी"),
    ("Assiduous", "adjective", "Showing great care and perseverance.", "परिश्रमी"),
    ("Atrophy", "verb", "Gradually decline in effectiveness or vigor due to underuse or neglect.", "क्षय होना"),
    ("Avarice", "noun", "Extreme greed for wealth or material gain.", "लालच / लोभ"),
    ("Banal", "adjective", "So lacking in originality as to be obvious and boring.", "साधारण / मामूली"),
    ("Belligerent", "adjective", "Hostile and aggressive.", "युद्धरत / लड़ाकू"),
    ("Benevolent", "adjective", "Well meaning and kindly.", "परोपकारी"),
    ("Boisterous", "adjective", "Noisy, energetic, and cheerful; rowdy.", "कोलाहलपूर्ण"),
    ("Bombastic", "adjective", "High-sounding but with little meaning; inflated.", "आडंबरपूर्ण"),
    ("Brevity", "noun", "Concise and exact use of words in writing or speech.", "संक्षिप्तता"),
    ("Cacophony", "noun", "A harsh discordant mixture of sounds.", "कोलाहल / कर्कश ध्वनि"),
    ("Cajole", "verb", "Persuade (someone) to do something by sustained coaxing or flattery.", "फुसलाना"),
    ("Candor", "noun", "The quality of being open and honest in expression; frankness.", "निष्कपटता"),
    ("Capricious", "adjective", "Given to sudden and unaccountable changes of mood or behavior.", "मनमौजी / चंचल"),
    ("Castigate", "verb", "Reprimand (someone) severely.", "फटकारना"),
    ("Catalyst", "noun", "A person or thing that precipitates an event.", "उत्प्रेरक"),
    ("Caustic", "adjective", "Sarcastic in a scathing and bitter way.", "व्यंग्यात्मक"),
    ("Chicanery", "noun", "The use of trickery to achieve a political, financial, or legal purpose.", "छल-कपट"),
    ("Circumspect", "adjective", "Wary and unwilling to take risks.", "एहतियात बरतने वाला"),
    ("Clandestine", "adjective", "Kept secret or done secretively.", "गुप्त"),
    ("Coalesce", "verb", "Come together to form one mass or whole.", "संगठित होना"),
    ("Cogent", "adjective", "Clear, logical, and convincing.", "ठोस / प्रभावशाली"),
    ("Complacent", "adjective", "Showing smug or uncritical satisfaction with oneself.", "आत्मसंतुष्ट"),
    ("Conciliatory", "adjective", "Intended or likely to placate or pacify.", "मैत्रीपूर्ण / समझौताकारी"),
    ("Conundrum", "noun", "A confusing and difficult problem or question.", "पहेली / मुश्किल"),
    ("Copious", "adjective", "Abundant in supply or quantity.", "प्रचुर / बहुत अधिक"),
    ("Corroborate", "verb", "Confirm or give support to (a statement, theory, or finding).", "पुष्टि करना"),
    ("Cursory", "adjective", "Hasty and therefore not thorough or detailed.", "सरसरी"),
    ("Dearth", "noun", "A scarcity or lack of something.", "अकाल / कमी"),
    ("Debacle", "noun", "A sudden and ignominious failure; a fiasco.", "पराजय / असफलता"),
    ("Deferential", "adjective", "Showing deference; respectful.", "आदरपूर्ण"),
    ("Delineate", "verb", "Describe or portray (something) precisely.", "सटीक वर्णन करना"),
    ("Demagogue", "noun", "A political leader who seeks support by appealing to desires of ordinary people.", "दुर्जन नेता"),
    ("Despot", "noun", "A ruler or person who holds absolute power, typically one who exercises it in a cruel way.", "तानाशाह"),
    ("Diaphanous", "adjective", "Light, delicate, and translucent.", "पारभासी"),
    ("Dictum", "noun", "A formal pronouncement from an authoritative source.", "कथन / आदेश"),
    ("Didactic", "adjective", "Intended to teach, particularly in having moral instruction as an ulterior motive.", "शिक्षाप्रद"),
    ("Diffident", "adjective", "Modest or shy because of a lack of self-confidence.", "संकोची / शर्मीला"),
    ("Digress", "verb", "Leave the main subject temporarily in speech or writing.", "विषयांतर होना"),
    ("Disparate", "adjective", "Essentially different in kind; not allowing comparison.", "भिन्न / असमान"),
    ("Disseminate", "verb", "Spread or disperse (something, especially information) widely.", "प्रसार करना"),
    ("Dissonance", "noun", "Lack of harmony among musical notes.", "असंगति"),
    ("Docile", "adjective", "Ready to accept control or instruction; submissive.", "विनीत / दब्बू"),
    ("Dogmatic", "adjective", "Inclined to lay down principles as undeniably true.", "कट्टर / सिद्धांतवादी"),
    ("Dormant", "adjective", "Having normal physical functions suspended or slowed down for a period of time.", "सुप्त / निष्क्रिय"),
    ("Ebullient", "adjective", "Cheerful and full of energy.", "उत्साही / प्रफुल्लित"),
    ("Eclectic", "adjective", "Deriving ideas, style, or taste from a broad and diverse range of sources.", "उदार / चयनशील"),
    ("Edify", "verb", "Instruct or improve (someone) morally or intellectually.", "शिक्षा देना / सुधारना"),
    ("Efface", "verb", "Erase (a mark) from a surface.", "मिटाना"),
    ("Effigy", "noun", "A sculpture or model of a person.", "पुतला"),
    ("Egregious", "adjective", "Outstandingly bad; shocking.", "भीषण / अत्यंत बुरा"),
    ("Elicit", "verb", "Evoke or draw out (a response, answer, or fact) from someone.", "प्रकाश में लाना / प्राप्त करना"),
    ("Eloquent", "adjective", "Fluent or persuasive in speaking or writing.", "सुवक्ता"),
    ("Elusive", "adjective", "Difficult to find, catch, or achieve.", "पकड़ में न आने वाला"),
    ("Emancipate", "verb", "Set free from legal, social, or political restrictions.", "स्वतंत्र करना"),
    ("Emulate", "verb", "Match or surpass (a person or achievement), typically by imitation.", "अनुकरण करना"),
    ("Enervate", "verb", "Cause (someone) to feel drained of energy or vitality.", "कमजोर करना"),
    ("Engender", "verb", "Cause or give rise to (a feeling, situation, or condition).", "उत्पन्न करना"),
    ("Enigma", "noun", "A person or thing that is mysterious, puzzling, or difficult to understand.", "पहेली / रहस्य"),
    ("Ephemeral", "adjective", "Lasting for a very short time.", "अल्पकालिक"),
    ("Equanimity", "noun", "Mental calmness, composure, and evenness of temper.", "धैर्य / समभाव"),
    ("Equivocal", "adjective", "Open to more than one interpretation; ambiguous.", "अस्पष्ट / गोलमोल"),
    ("Erudite", "adjective", "Having or showing great knowledge or learning.", "विद्वान"),
    ("Esoteric", "adjective", "Intended for or likely to be understood by only a small number of people.", "गूढ़ / गुप्त"),
    ("Euphemism", "noun", "A mild or indirect word or expression substituted for one considered to be too harsh.", "कोमल वचन"),
    ("Exacerbate", "verb", "Make (a problem, bad situation, or negative feeling) worse.", "बिगाड़ना / और अधिक खराब करना"),
    ("Exacting", "adjective", "Making great demands on one's skill, attention, or other resources.", "कठिन / मांगपूर्ण"),
    ("Exculpate", "verb", "Show or declare that (someone) is not guilty of wrongdoing.", "दोषमुक्त करना"),
    ("Exorbitant", "adjective", "Unreasonably high.", "अत्यधिक / बहुत ज़्यादा"),
    ("Expedient", "adjective", "Convenient and practical although possibly improper or immoral.", "उचित / लाभप्रद"),
    ("Explicit", "adjective", "Stated clearly and in detail, leaving no room for confusion or doubt.", "स्पष्ट / मुखर"),
    ("Extol", "verb", "Praise enthusiastically.", "प्रशंसा करना"),
    ("Extraneous", "adjective", "Irrelevant or unrelated to the subject being dealt with.", "अप्रासंगिक / बाहरी"),
    ("Exult", "verb", "Show or feel elation or jubilation, especially as the result of a success.", "अति प्रसन्न होना"),
    ("Facetious", "adjective", "Treating serious issues with deliberately inappropriate humor.", "हंसोड़ / दिल्लगीबाज"),
    ("Fallacious", "adjective", "Based on a mistaken belief.", "गलत / भ्रामक"),
    ("Fastidious", "adjective", "Very attentive to and concerned about accuracy and detail.", "नखरेबाज / तुनकमिजाज"),
    ("Fervent", "adjective", "Having or displaying a passionate intensity.", "उत्साही / गर्मजोशीपूर्ण"),
    ("Fickle", "adjective", "Changing frequently, especially as regards one's loyalties, interests, or affection.", "चंचल / अस्थिर"),
    ("Fortuitous", "adjective", "Happening by a lucky chance; fortunate.", "आकस्मिक / भाग्यशाली"),
    ("Fractious", "adjective", "Irritable and quarrelsome.", "झगड़ालू"),
    ("Frivolous", "adjective", "Not having any serious purpose or value.", "तुच्छ / हल्का"),
    ("Frugal", "adjective", "Sparing or economical with regard to money or food.", "किफायती / मितव्ययी"),
    ("Furtive", "adjective", "Attempting to avoid notice or attention, typically because of guilt.", "चुपके से / गुप्त"),
    ("Garrulous", "adjective", "Excessively talkative, especially on trivial matters.", "बातूनी"),
    ("Gourmet", "noun", "A connoisseur of good food.", "भोजन का पारखी"),
    ("Gratuitous", "adjective", "Uncalled for; lacking good reason; unwarranted.", "अकारण / अनावश्यक"),
    ("Gregarious", "adjective", "Fond of company; sociable.", "मिलनसार"),
    ("Guile", "noun", "Sly or cunning intelligence.", "छल-कपट / धूर्तता"),
    ("Hacker", "noun", "A person who uses computers to gain unauthorized access to data.", "हैकर"),
    ("Hackneyed", "adjective", "Lacking significance through having been overused; unoriginal.", "घिसा-पिटा / साधारण"),
    ("Hallowed", "adjective", "Made holy; consecrated.", "पवित्र"),
    ("Haphazard", "adjective", "Lacking any obvious principle of organization.", "बेतरतीब"),
    ("Harangue", "noun", "A lengthy and aggressive speech.", "आक्रामक भाषण"),
    ("Hedonist", "noun", "A person who believes that the pursuit of pleasure is the most important aspect of life.", "सुखवादी"),
    ("Heinous", "adjective", "Utterly odious or wicked.", "जघन्य / घृणित"),
    ("Hermetic", "adjective", "Complete and airtight.", "वायुरुद्ध / गुप्त"),
    ("Hiatus", "noun", "A pause or gap in a sequence, series, or process.", "अंतराल / विराम"),
    ("Homage", "noun", "Special honor or respect shown publicly.", "श्रद्धांजलि / सम्मान"),
    ("Hubris", "noun", "Excessive pride or self-confidence.", "अभिमान / घमंड"),
    ("Hyperbole", "noun", "Exaggerated statements or claims not meant to be taken literally.", "अतिशयोक्ति"),
    ("Iconoclast", "noun", "A person who attacks cherished beliefs or institutions.", "मूर्तिभंजक / पंथ-विरोधी"),
    ("Idiosyncrasy", "noun", "A mode of behavior or way of thought peculiar to an individual.", "विचित्रता / लत"),
    ("Ignominious", "adjective", "Deserving or causing public disgrace or shame.", "घृणित / अपमानजनक"),
    ("Immutable", "adjective", "Unchanging over time or unable to be changed.", "अपरिवर्तनीय"),
    ("Impeccable", "adjective", "In accordance with the highest standards; faultless.", "त्रुटिहीन / निर्दोष"),
    ("Impediment", "noun", "A hindrance or obstruction in doing something.", "बाधा"),
    ("Imperious", "adjective", "Assuming power or authority without justification; arrogant and domineering.", "शाही / अभिमानी"),
    ("Imperturbable", "adjective", "Unable to be upset or excited; calm.", "अडिग / शांत"),
    ("Impervious", "adjective", "Not allowing fluid to pass through.", "अभेद्य / अप्रभावित"),
    ("Impetuous", "adjective", "Acting or done quickly and without thought or care.", "अवेगी / उतावला"),
    ("Implacable", "adjective", "Relentless; unstoppable.", "कठोर / जिसे संतुष्ट न किया जा सके"),
    ("Implicit", "adjective", "Implied though not plainly expressed.", "अंतर्निहित"),
    ("Impromptu", "adjective", "Done without being planned, organized, or rehearsed.", "बिना तैयारी के"),
    ("Inadvertent", "adjective", "Not resulting from or achieved through deliberate planning.", "अनजाने में"),
    ("Inane", "adjective", "Silly; stupid.", "बेवकूफी भरा / अर्थहीन"),
    ("Inchoate", "adjective", "Just begun and so not fully formed or developed.", "अविकसित / प्रारंभिक"),
    ("Incisive", "adjective", "Intelligently analytical and clear-thinking.", "तीक्ष्ण / प्रभावशाली"),
    ("Incongruous", "adjective", "Not in harmony or keeping with the surroundings.", "बेमेल / असंगत"),
    ("Indigenous", "adjective", "Originating or occurring naturally in a particular place; native.", "स्वदेशी / मूल"),
    ("Indigent", "adjective", "Poor; needy.", "दरिद्र / गरीब"),
    ("Indolent", "adjective", "Wanting to avoid activity or exertion; lazy.", "सुस्त / आलसी"),
    ("Ineffable", "adjective", "Too great or extreme to be expressed or described in words.", "अवर्णनीय"),
    ("Inert", "adjective", "Lacking the ability or strength to move.", "निष्क्रिय"),
    ("Inexorable", "adjective", "Impossible to stop or prevent.", "अपरिवर्तनीय / कठोर"),
    ("Inference", "noun", "A conclusion reached on the basis of evidence and reasoning.", "निष्कर्ष / अनुमान"),
    ("Ingenuous", "adjective", "Innocent and unsuspecting.", "सरल / निष्कपट"),
    ("Inherent", "adjective", "Existing in something as a permanent, essential, or characteristic attribute.", "अंतर्निहित"),
    ("Innocuous", "adjective", "Not harmful or offensive.", "अहानिकर / निर्दोष"),
    ("Inscrutable", "adjective", "Impossible to understand or interpret.", "रहस्यमय / अगम्य"),
    ("Insidiuos", "adjective", "Proceeding in a gradual, subtle way, but with harmful effects.", "कपटी / घातक"),
    ("Insipid", "adjective", "Lacking flavor.", "फीका / नीरस"),
    ("Intransigent", "adjective", "Unwilling or refusing to change one's views or to agree about something.", "कट्टर / अडिग"),
    ("Intrepid", "adjective", "Fearless; adventurous.", "निडर / साहसी"),
    ("Inundate", "verb", "Overwhelm (someone) with things or people to be dealt with.", "बाढ़ लाना / अभिभूत करना"),
    ("Inure", "verb", "Accustom (someone) to something, especially something unpleasant.", "अभ्यस्त करना"),
    ("Inveterate", "adjective", "Having a particular habit, activity, or interest that is long-established and unlikely to change.", "कट्टर / पक्का"),
    ("Irascible", "adjective", "Having or showing a tendency to be easily angered.", "चिड़चिड़ा"),
    ("Judicious", "adjective", "Having, showing, or done with good judgment or sense.", "विवेकपूर्ण"),
    ("Juxtaposition", "noun", "The fact of two things being seen or placed close together with contrasting effect.", "नजदीकी / तुलनात्मक स्थिति"),
    ("Kindle", "verb", "Light or set on fire.", "प्रज्वलित करना"),
    ("Kinetic", "adjective", "Relating to or resulting from motion.", "गतिज"),
    ("Knell", "noun", "The sound of a bell, especially when rung solemnly for a death or funeral.", "शोक की घंटी"),
    ("Laconic", "adjective", "Using very few words.", "मितभाषी / संक्षिप्त"),
    ("Lament", "noun", "A passionate expression of grief or sorrow.", "विलाप करना"),
    ("Languid", "adjective", "Displaying or having a disinclination for physical exertion or effort; slow and relaxed.", "सुस्त / निस्तेज"),
    ("Larceny", "noun", "Theft of personal property.", "चोरी"),
    ("Latent", "adjective", "Existing but not yet developed or manifest; hidden or concealed.", "गुप्त / प्रसुप्त"),
    ("Laud", "verb", "Praise (a person or their achievements) highly, especially in a public context.", "प्रशंसा करना"),
    ("Legacy", "noun", "An amount of money or property left to someone in a will.", "विरासत"),
    ("Lethargic", "adjective", "Affected by lethargy; sluggish and apathetic.", "सुस्त / आलसी"),
    ("Levity", "noun", "Humor or frivolity, especially the treatment of a serious matter with humor or lack of due respect.", "छिछोरापन / हास्य"),
    ("Liaison", "noun", "Communication or cooperation which facilitates a close working relationship between people or organizations.", "संपर्क / तालमेल"),
    ("Listless", "adjective", "Lacking energy or enthusiasm.", "निरुत्साहित"),
    ("Loquacious", "adjective", "Tending to talk a great deal; talkative.", "बातूनी"),
    ("Lucid", "adjective", "Expressed clearly; easy to understand.", "स्पष्ट / सुबोध"),
    ("Luminous", "adjective", "Full of or shedding light; bright or shining, especially in the dark.", "चमकीला"),
    ("Magnanimous", "adjective", "Generous or forgiving, especially toward a rival or less powerful person.", "उदार"),
    ("Malevolent", "adjective", "Having or showing a wish to do evil to others.", "द्रोही / बुरा चाहने वाला"),
    ("Malleable", "adjective", "Able to be hammered or pressed permanently out of shape without breaking or cracking.", "लचीला / आघातवर्धनीय"),
    ("Manifest", "adjective", "Clear or obvious to the eye or mind.", "स्पष्ट / प्रकट"),
    ("Maudlin", "adjective", "Self-pityingly or tearfully sentimental, often through drunkenness.", "भावुक / रोनी सूरत वाला"),
    ("Maverick", "noun", "An unorthodox or independent-minded person.", "स्वतंत्र विचारों वाला"),
    ("Meander", "verb", "Follow a winding course.", "घूमना-फिरना / घुमावदार होना"),
    ("Melancholy", "noun", "A feeling of pensive sadness, typically with no obvious cause.", "उदासी"),
    ("Mendacious", "adjective", "Not telling the truth; lying.", "मिथ्यावादी / झूठा"),
    ("Meticulous", "adjective", "Showing great attention to detail; very careful and precise.", "अति सावधान / सूक्ष्म"),
    ("Misanthrope", "noun", "A person who dislikes humankind and avoids human society.", "मानवद्वेषी"),
    ("Mitigate", "verb", "Make less severe, serious, or painful.", "कम करना / शांत करना"),
    ("Mollify", "verb", "Appease the anger or anxiety of (someone).", "शांत करना / नरम करना"),
    ("Morose", "adjective", "Sullen and ill-tempered.", "चिड़चिड़ा / उदास"),
    ("Mundane", "adjective", "Lacking interest or excitement; dull.", "साधारण / सांसारिक"),
    ("Munificent", "adjective", "Larger or more generous than is usual or necessary.", "अत्यधिक उदार / दानी"),
    ("Myopic", "adjective", "Nearsighted.", "अदूरदर्शी"),
    ("Nadir", "noun", "The lowest point in the fortunes of a person or organization.", "पतन / अधोबिंदु"),
    ("Naïve", "adjective", "Showing a lack of experience, wisdom, or judgment.", "सीधा / अनुभवहीन"),
    ("Narcissism", "noun", "Excessive interest in or admiration of oneself and one's physical appearance.", "आत्ममोह"),
    ("Nebulous", "adjective", "In the form of a cloud or haze; hazy.", "अस्पष्ट / धुंधला"),
    ("Nefarious", "adjective", "Wicked or criminal.", "कुटिल / अपराधी"),
    ("Negligent", "adjective", "Failing to take proper care in doing something.", "लापरवाह"),
    ("Neophyte", "noun", "A person who is new to a subject, skill, or belief.", "नौसिखिया"),
    ("Nostalgia", "noun", "A sentimental longing or wistful affection for the past.", "अतीत की याद"),
    ("Noxious", "adjective", "Harmful, poisonous, or very unpleasant.", "हानिकारक / विषैला"),
    ("Nuance", "noun", "A subtle difference in or shade of meaning, expression, or sound.", "सूक्ष्म अंतर"),
    ("Obdurate", "adjective", "Stubbornly refusing to change one's opinion or course of action.", "जिद्दी / कठोर"),
    ("Obfuscate", "verb", "Render obscure, unclear, or unintelligible.", "अस्पष्ट करना / भ्रमित करना"),
    ("Oblivion", "noun", "The state of being unaware or unconscious of what is happening.", "विस्मृति / गुमनामी"),
    ("Obsequious", "adjective", "Obedient or attentive to an excessive or servile degree.", "चापलूस / आज्ञाकारी"),
    ("Obsolete", "adjective", "No longer produced or used; out of date.", "अप्रचलित"),
    ("Obstinate", "adjective", "Stubbornly refusing to change one's opinion or chosen course of action, despite attempts to persuade one to do so.", "जिद्दी"),
    ("Obviate", "verb", "Remove (a need or difficulty).", "निवारण करना / दूर करना"),
    ("Ominous", "adjective", "Giving the impression that something bad or unpleasant is going to happen; threatening.", "अशुभ"),
    ("Opaque", "adjective", "Not able to be seen through; not transparent.", "अपारदर्शी"),
    ("Opprobrium", "noun", "Harsh criticism or censure.", "तिरस्कार / अपमान"),
    ("Opulence", "noun", "Great wealth or luxuriousness.", "समृद्धि / वैभव"),
    ("Ostentatious", "adjective", "Characterized by vulgar or pretentious display; designed to impress or attract notice.", "दिखावटी / आडंबरपूर्ण"),
    ("Palliate", "verb", "Make (a disease or its symptoms) less severe or unpleasant without removing the cause.", "कम करना / हल्का करना"),
    ("Panacea", "noun", "A solution or remedy for all difficulties or diseases.", "रामबाण"),
    ("Paradigm", "noun", "A typical example or pattern of something; a model.", "उदाहरण / आदर्श"),
    ("Paradox", "noun", "A seemingly absurd or self-contradictory statement or proposition that when investigated or explained may prove to be well founded or true.", "विरोधाभास"),
    ("Paragon", "noun", "A person or thing viewed as a model of excellence.", "आदर्श / मिसाल"),
    ("Pariah", "noun", "An outcast.", "अछूत / बहिष्कृत व्यक्ति"),
    ("Parsimonious", "adjective", "Unwilling to spend money or use resources; stingy or frugal.", "किफायती / कंजूस"),
    ("Paucity", "noun", "The presence of something only in small or insufficient quantities or amounts; scarcity.", "कमी"),
    ("Peccadillo", "noun", "A small, relatively unimportant offense or sin.", "छोटी भूल"),
    ("Pedantic", "adjective", "Of or like a pedant.", "पांडित्य-दिखाने वाला"),
    ("Pellucid", "adjective", "Translucently clear.", "निर्मल / स्पष्ट"),
    ("Penchant", "noun", "A strong or habitual liking for something or tendency to do something.", "विशेष रुचि / झुकाव"),
    ("Penitent", "adjective", "Feeling or showing sorrow and regret for having done something wrong.", "पछतावा करने वाला"),
    ("Pensive", "adjective", "Engaged in, involving, or reflecting deep or serious thought.", "विचारमग्न"),
    ("Perfunctory", "adjective", "Carried out with a minimum of effort or reflection.", "लापरवाह / सरसरी"),
    ("Permeate", "verb", "Spread throughout (something); pervade.", "व्याप्त होना"),
    ("Pervasive", "adjective", "Spreading widely throughout an area or a group of people.", "व्यापक"),
    ("Philanthropy", "noun", "The desire to promote the welfare of others, expressed by the generous donation of money to good causes, or by good customs.", "परोपकार"),
    ("Pious", "adjective", "Devoutly religious.", "पवित्र / धर्मपरायण"),
    ("Placid", "adjective", "Not easily upset or excited.", "शांत"),
    ("Plethora", "noun", "A large or excessive amount of (something).", "बहुतायत / अधिकता"),
    ("Pragmatic", "adjective", "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.", "व्यावहारिक"),
    ("Precarious", "adjective", "Not securely held or in position; dangerously likely to fall or collapse.", "अनिश्चित / खतरनाक"),
    ("Precipice", "noun", "A very steep rock face or cliff, typically a very tall one.", "खड़ी चट्टान"),
    ("Precocious", "adjective", "Having developed certain abilities or proclivities at an earlier age than usual.", "अकालप्रौढ़ / तेज बुद्धि वाला"),
    ("Precursor", "noun", "A person or thing that comes before another of the same kind; a forerunner.", "अग्रदूत"),
    ("Predilection", "noun", "A preference or special liking for something; a bias in favor of something.", "झुकाव / पसंद"),
    ("Pretentious", "adjective", "Attempting to impress by affecting greater importance, talent, culture, etc., than is actually possessed.", "दिखावटी"),
    ("Prevalent", "adjective", "Widespread in a particular area at a particular time.", "प्रचलित"),
    ("Pristine", "adjective", "In its original condition; unspoiled.", "नया / मौलिक"),
    ("Probity", "noun", "The quality of having strong moral principles; honesty and decency.", "ईमानदारी"),
    ("Proclivity", "noun", "A tendency to choose or do something regularly; an inclination or predisposition toward a particular thing.", "झुकाव"),
    ("Procrastinate", "verb", "Delay or postpone action; put off doing something.", "टालमटोल करना"),
    ("Prodigal", "adjective", "Spending money or resources freely and recklessly; wastefully extravagant.", "फिजूलखर्च"),
    ("Prodigious", "adjective", "Remarkably or impressively great in extent, size, or degree.", "अद्भुत / विशाल"),
    ("Profound", "adjective", "Very great or intense.", "गहन / गहरा"),
    ("Prolific", "adjective", "Producing much fruit or foliage or many offspring.", "बहुप्रज / फलदायक"),
    ("Propensity", "noun", "An inclination or natural tendency to behave in a particular way.", "झुकाव / प्रवृत्ति"),
    ("Propitious", "adjective", "Giving or indicating a good chance of success; favorable.", "अनुकूल / मंगलकारी"),
    ("Prosaic", "adjective", "Having the style or diction of prose; lacking poetic beauty.", "नीरस / साधारण"),
    ("Prosperity", "noun", "The state of being prosperous.", "समृद्धि"),
    ("Provocative", "adjective", "Causing annoyance, anger, or another strong reaction, especially deliberately.", "उत्तेजक"),
    ("Prudence", "noun", "The quality of being prudent; cautiousness.", "विवेक / सावधानी"),
    ("Puerile", "adjective", "Childishly silly and trivial.", "बचकानी / तुच्छ"),
    ("Pugnacious", "adjective", "Eager or quick to argue, quarrel, or fight.", "झगड़ालू"),
    ("Punctilious", "adjective", "Showing great attention to detail or correct behavior.", "समयनिष्ठ / अति सावधान"),
    ("Pungent", "adjective", "Having a sharply strong taste or smell.", "तीखा / कटु"),
    ("Quaint", "adjective", "Attractively unusual or old-fashioned.", "विचित्र / पुराना"),
    ("Querulous", "adjective", "Complaining in a petulant or whining manner.", "शिकायती"),
    ("Quiescent", "adjective", "In a state or period of inactivity or dormancy.", "मौन / शांत"),
    ("Quixotic", "adjective", "Exceedingly idealistic; unrealistic and impractical.", "विलक्षण / अव्यावहारिक"),
    ("Rancor", "noun", "Bitterness or resentfulness, especially when long-standing.", "विद्वेष / शत्रुता"),
    ("Rebuff", "verb", "Reject (someone or something) in an abrupt or ungracious manner.", "अस्वीकार करना"),
    ("Recalcitrant", "adjective", "Having an obstinately uncooperative attitude toward authority or discipline.", "आज्ञा न मानने वाला"),
    ("Recant", "verb", "Say that one no longer holds an opinion or belief, especially one considered unorthodox.", "त्यागना / खंडन करना"),
    ("Recluse", "noun", "A person who lives a solitary life and tends to avoid other people.", "वैरागी / एकांतवासी"),
    ("Recondite", "adjective", "Little known; abstruse.", "गूढ़ / अस्पष्ट"),
    ("Redoubtable", "adjective", "Formidable, especially as an opponent.", "भयानक / दुर्जेय"),
    ("Refute", "verb", "Prove (a statement or theory) to be wrong or false; disprove.", "खंडन करना"),
    ("Reiterate", "verb", "Say something again or a number of times, typically for emphasis or clarity.", "दोहराना"),
    ("Renovate", "verb", "Restore (something old, especially a building) to a good state of repair.", "नवीनीकरण करना"),
    ("Reprehensible", "adjective", "Deserving censure or condemnation.", "निंदनीय"),
    ("Repudiate", "verb", "Refuse to accept or be associated with.", "अस्वीकार करना"),
    ("Resilient", "adjective", "Able to withstand or recover quickly from difficult conditions.", "लचीला"),
    ("Reticent", "adjective", "Not revealing one's thoughts or feelings readily.", "अल्पभाषी / चुप रहने वाला"),
    ("Reverence", "noun", "Deep respect for someone or something.", "श्रद्धा / आदर"),
    ("Rhetoric", "noun", "The art of effective or persuasive speaking or writing, especially the use of figures of speech and other compositional techniques.", "बयानबाजी / अलंकार"),
    ("Saccarine", "adjective", "Excessively sweet or sentimental.", "अति मीठा / भावुक"),
    ("Sacrosanct", "adjective", "Regarded as too important or valuable to be interfered with.", "अति पवित्र"),
    ("Sagacious", "adjective", "Having or showing keen mental discernment and good judgment; shrewd.", "बुद्धिमान / चतुर"),
    ("Salient", "adjective", "Most noticeable or important.", "मुख्य / प्रमुख"),
    ("Sanctimonious", "adjective", "Making a show of being morally superior to other people.", "पाखंडी / ढोंगी"),
    ("Satiate", "verb", "Satisfied to the full; sated.", "तृप्त करना"),
    ("Scrutinize", "verb", "Examine or inspect closely and thoroughly.", "जांचना / सूक्ष्म परीक्षण करना"),
    ("Sedentary", "adjective", "Tending to spend much time seated; somewhat inactive.", "गतिहीन / सुस्त"),
    ("Serendipity", "noun", "The occurrence and development of events by chance in a happy or beneficial way.", "आकस्मिक लाभ"),
    ("Servile", "adjective", "Having or showing an excessive willingness to serve or please others.", "चापलूसी भरा / दासत्व"),
    ("Skeptic", "noun", "A person inclined to question or doubt all accepted opinions.", "संदेहवादी"),
    ("Solicitous", "adjective", "Showing interest or concern.", "चिंतित / उत्सुक"),
    ("Soporific", "adjective", "Tending to induce drowsiness or sleep.", "नींद लाने वाला"),
    ("Specious", "adjective", "Plausible but wrong.", "दिखावटी / भ्रामक"),
    ("Sporadic", "adjective", "Occurring at irregular intervals or only in a few places; scattered or isolated.", "छिटपुट"),
    ("Spurious", "adjective", "Not being what it purports to be; false or fake.", "नकली / जाली"),
    ("Stolid", "adjective", "Calm, dependable, and showing little emotion or animation.", "सुस्त / बेपरवाह"),
    ("Strident", "adjective", "Loud and harsh; grating.", "कर्कश"),
    ("Stupefy", "verb", "Make (someone) unable to think or feel properly.", "हैरान करना / सुन्न करना"),
    ("Subjugate", "verb", "Bring under domination or control, especially by conquest.", "अधीन करना / जीतना"),
    ("Sublime", "adjective", "Of such excellence, grandeur, or beauty as to inspire great admiration and awe.", "उत्कृष्ट / भव्य"),
    ("Succinct", "adjective", "Briefly and clearly expressed.", "संक्षिप्त / स्पष्ट"),
    ("Supercilious", "adjective", "Behaving or looking as though one thinks one is superior to others.", "घमंडी / अभिमानी"),
    ("Superfluous", "adjective", "Unnecessary, especially through being more than enough.", "अनावश्यक / फ़ालतू"),
    ("Surreptitious", "adjective", "Kept secret, especially because it would not be approved of.", "गुप्त / चुपके से"),
    ("Sycophant", "noun", "A person who acts obsequiously toward someone important in order to gain advantage.", "चापलूस"),
    ("Tacit", "adjective", "Understood or implied without being stated.", "मौन / अंतर्निहित"),
    ("Taciturn", "adjective", "Reserved or uncommunicative in speech; saying little.", "अल्पभाषी"),
    ("Tantalize", "verb", "Torment or tease (someone) with the sight or promise of something that is unobtainable.", "तरसाना"),
    ("Tenuous", "adjective", "Very weak or slight.", "तुच्छ / पतला"),
    ("Terse", "adjective", "Sparing in the use of words; abrupt.", "संक्षिप्त"),
    ("Timorous", "adjective", "Showing or suffering from nervousness, fear, or a lack of confidence.", "डरपोक"),
    ("Tirade", "noun", "A long, angry speech of criticism or accusation.", "कड़ी निंदा"),
    ("Torpid", "adjective", "Mentally or physically inactive; lethargic.", "सुस्त / सुप्त"),
    ("Tractable", "adjective", "Easy to control or influence.", "कोमल / विनीत"),
    ("Transient", "adjective", "Lasting only for a short time; impermanent.", "क्षणिक / अस्थाई"),
    ("Trepidation", "noun", "A feeling of fear or agitation about something that may happen.", "घबराहट / भय"),
    ("Trite", "adjective", "Lacking originality or freshness; dull on account of overuse.", "घिसा-पिटा"),
    ("Truculent", "adjective", "Eager or quick to argue or fight; aggressively defiant.", "लड़ाकू / निर्दयी"),
    ("Ubiquitous", "adjective", "Present, appearing, or found everywhere.", "सर्वव्यापी"),
    ("Uncanny", "adjective", "Strange or mysterious, especially in an unsettling way.", "विचित्र / अलौकिक"),
    ("Unconscionable", "adjective", "Not right or reasonable.", "अनुचित / अनैतिक"),
    ("Unctuous", "adjective", "Excessively or ingratiatingly flattering; oily.", "चापलूस / चिकना"),
    ("Upbraid", "verb", "Find fault with (someone); scold.", "फटकारना"),
    ("Usurp", "verb", "Take (a position of power or importance) illegally or by force.", "हड़पना"),
    ("Vacillate", "verb", "Alternate or waver between different opinions or actions; be indecisive.", "हिचकिचाना / डगमगाना"),
    ("Vacuous", "adjective", "Having or showing a lack of thought or intelligence; mindless.", "शून्य / खाली"),
    ("Venerate", "verb", "Regard with great respect; revere.", "सम्मान करना"),
    ("Veracity", "noun", "Conformity to facts; accuracy.", "सच्चाई / सत्यता"),
    ("Verbose", "adjective", "Using or expressed in more words than are needed.", "शब्दबहुल / वाचाल"),
    ("Vex", "verb", "Make (someone) feel annoyed, frustrated, or worried, especially with trivial matters.", "परेशान करना"),
    ("Vicarious", "adjective", "Experienced in the imagination through the feelings or actions of another person.", "प्रतिनिधिक / परोक्ष"),
    ("Vigilant", "adjective", "Keeping careful watch for possible danger or difficulties.", "जागरूक / सतर्क"),
    ("Vilify", "verb", "Speak or write about in an abusively disparaging manner.", "बदनाम करना"),
    ("Vindicat", "verb", "Clear (someone) of blame or suspicion.", "साबित करना / निर्दोष ठहराना"),
    ("Vindictive", "adjective", "Having or showing a strong or unreasoning desire for revenge.", "प्रतिशोधी"),
    ("Virtuoso", "noun", "A person highly skilled in music or another artistic pursuit.", "कलाप्रवीण व्यक्ति"),
    ("Virulent", "adjective", "Extremely severe or harmful in its effects.", "विषैला / घातक"),
    ("Visceral", "adjective", "Relating to deep inward feelings rather than to the intellect.", "आंतरिक / स्वाभाविक"),
    ("Vitriolic", "adjective", "Filled with bitter criticism or malice.", "कटु / व्यंग्यात्मक"),
    ("Vituperate", "verb", "Blame or insult (someone) in strong or violent language.", "गाली देना / फटकारना"),
    ("Vociferous", "adjective", "Vehement or clamorous.", "मुखर / शोर मचाने वाला"),
    ("Volatile", "adjective", "Liable to change rapidly and unpredictably, especially for the worse.", "अस्थिर / परिवर्तनशील"),
    ("Voluble", "adjective", "Speaking or spoken incessantly and fluently.", "वाचाल / धाराप्रवाह"),
    ("Voracious", "adjective", "Wanting or devouring great quantities of food.", "पेटू / लालची"),
    ("Wanderlust", "noun", "A strong desire to travel.", "यात्रा की लालसा"),
    ("Wary", "adjective", "Feeling or showing caution about possible dangers or problems.", "सावधान / सतर्क"),
    ("Waver", "verb", "Become unsteady or unreliable.", "डिगना / हिचकिचाना"),
    ("Whimsical", "adjective", "Playfully quaint or fanciful, especially in an appealing and amusing way.", "मनमौजी / सनकी"),
    ("Wily", "adjective", "Skilled at gaining an advantage, especially deceitfully.", "धूर्त / चालाक"),
    ("Winsome", "adjective", "Attractive or appealing in appearance or character.", "मनोहर / आकर्षक"),
    ("Wizened", "adjective", "Shriveled or wrinkled with age.", "मुरझाया हुआ"),
    ("Wrath", "noun", "Extreme anger.", "क्रोध"),
    ("Zealot", "noun", "A person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.", "कट्टरपंथी"),
    ("Zenith", "noun", "The time at which something is most powerful or successful.", "शिखर")
]

def generate_words_json():
    start_date = date(2026, 1, 1)
    end_date = date(2026, 12, 31)
    
    delta = end_date - start_date
    num_days = delta.days + 1
    
    json_data = []
    
    for i in range(num_days):
        current_date = start_date + timedelta(days=i)
        # Cycle through the words list if needed (it has ~250 words now, I will pad it or reuse)
        # Actually I should have 366 for 2026 (it's not a leap year, 365 days)
        # I'll use modulo to loop if list is shorter
        word_tuple = words_data[i % len(words_data)]
        
        json_data.append({
            "word": word_tuple[0],
            "part_of_speech": word_tuple[1],
            "definition": word_tuple[2],
            "hindi_meaning": word_tuple[3],
            "date": current_date.strftime("%Y-%m-%d")
        })
    
    with open('d:/Flutter Projects/shabd/assets/words.json', 'w', encoding='utf-8') as f:
        json.dump(json_data, f, ensure_ascii=False, indent=4)
        
    print(f"Successfully generated {len(json_data)} words in assets/words.json")

if __name__ == "__main__":
    generate_words_json()
